name: project
title: Projekt

options:
  changeSlug: true
  changeStatus: true
  changeTemplate: false
  changeTitle: true
  delete: true
  preview: false

columns:
  - 2/3: content
  - 1/3: images

sections:

  content:
    type: fields
    fields:
      title:
        label: Titel
        type: text
        width: 2/4
      client:
        label: Kunde
        type: text
        width: 1/4
      year:
        label: Jahr
        type: number
        min: 2000
        default: 2018
        required: true
        width: 1/4
      description:
        label: Beschreibung
        type: textarea
        size: small

  images:
    extends: sections/images
    headline: Fotos
    template: project-image
