name: project
title: Projekt

options:
  changeSlug: true
  changeStatus: true
  changeTemplate: false
  changeTitle: true
  delete: true
  preview: false

columns:
  # - width: 1/2
  # sections:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          title:
            label: Titel
            type: text
          client:
            label: Kunde
            type: text
            width: 1/2
          year:
            label: Jahr
            type: number
            min: 2000
            default: 2018
            required: true
            width: 1/2
          description:
            label: Beschreibung
            type: textarea
            size: small

  - width: 1/2
    sections:
      images:
        extends: sections/images
        headline: Fotos
        template: project-image
