name: project
title: Projekt

options:
  changeSlug: true
  changeStatus: true
  changeTemplate: false
  changeTitle: true
  delete: true
  preview: false

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          title:
            label: Titel
            type: text
            
          client:
            label: Kunde
            type: text
            width: 1/2

          year:
            label: Jahr
            type: number
            min: 2000
            default: 2018
            required: true
            width: 1/2

          description:
            label: Beschreibung
            type: textarea
            size: small

          cover:
            label: Übersicht
            type: files
            query: page.images
            required: true

          layouts:
            type: structure
            headline: Layouts
            fields:
              image1:
                headline: Foto 1
                type: select
                options: query
                query: page.files
                width: 1/2
              image2:
                headline: Foto 2
                type: select
                options: query
                query: page.files
                width: 1/2
              image3:
                headline: Foto 3
                type: select
                options: query
                query: page.files
                width: 1/2
              image4:
                headline: Foto 4
                type: select
                options: query
                query: page.files
                width: 1/2
              sizing:
                label: Layout
                type: select
                options:
                  fullbleed: Randabfallend
                  contained: Füllend
                  big: Groß

  - width: 1/3
    sections:
      images:
        extends: sections/images
        headline: Fotos
        template: project-image
