name: project
title: Projekt
preset: page

options:
  changeSlug: true
  changeStatus: true
  changeTemplate: false
  changeTitle: true
  delete: true
  preview: false

status:
  draft: Entwurf
  listed: Veröffentlicht

fields:
  title:
    label: Titel
    type: text

  client:
    label: Kunde
    type: text

  description:
    label: Beschreibung
    type: textarea
    size: small
    buttons:
      - italic
      - link
    maxlength: 200

  cover:
    label: Übersicht
    type: files
    query: page.images
    required: true
    help: Bitte möglichst viele Querformate auswählen

  layouts:
    type: structure
    label: Layouts
    required: true
    fields:
      images:
        label: Fotos
        type: files
        layout: cards
        background: white
        size: small
        query: page.images
        max: 3

sidebar:
  images:
    extends: files/default
    headline: Bildmaterial
