name: project
title: Projekt
preset: page

options:
  changeSlug: true
  changeStatus: true
  changeTemplate: false
  changeTitle: true
  delete: true
  preview: false

status:
  draft: Entwurf
  listed: Veröffentlicht

fields:
  title:
    label: Titel
    type: text

  client:
    label: Kunde
    type: text

  description:
    label: Beschreibung
    type: textarea
    size: small

  cover:
    label: Übersicht
    type: files
    query: page.images

  layouts:
    type: structure
    label: Layouts
    required: true
    fields:
      images:
        label: Fotos
        type: files
        query: page.images
        max: 3

sidebar:
  images:
    extends: sections/images
    headline: Fotos
