title: Site

tabs:
  pages:
    label: Content
    icon: page
    sections:
      projects:
        type: pages
        status: listed
        image: none
        layout: cards
        headline: Inhalte

  settings:
    label: Einstellungen
    icon: cog
    columns:

      - width: 2/3
        sections:
          meta:
            label: Einstellungen
            type: fields
            fields:
              metaTitle:
                label: Meta Title
                type: text
                required: true
              metaDescription:
                label: Meta Description
                type: textarea
                size: small
                maxlength: 150
              tags:
                label: Tags
                type: tags

      - width: 1/3
        sections:
          legal:
            type: fields
            fields:
              copyright:
                label: Copyright
                type: textarea
                size: small
                disabled: true
                buttons:
                  - link
              legal:
                label: Legal Notice
                type: textarea
                size: small
                required: true
