title: Site

tabs:
  pages:
    label: Projekte
    icon: page
    sections:
      projects:
        type: pages
        status: listed
        item:
          image: false
          info: "{{ page.template }}"

  settings:
    columns:
      - width: 2/3
        sections:
          settingsContent:
            label: Einstellungen
            type: fields
            fields:
              metaTitle:
                label: Meta Title
                type: text
                required: true
              metaDescription:
                label: Meta Description
                type: textarea
                size: small
                maxlength: 150
              tags:
                label: Tags
                type: tags

      - width: 1/3
        sections:
          settingsDefaults:
            type: fields
            fields:
              copyright:
                label: Copyright
                type: textarea
                size: small
                buttons:
                  - link
                disabled: false
